// Copyright 2018 The gVisor Authors.
// Modified for sandbox: private object types and byte-slice input.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package state

import (
	"bytes"
	"context"
	"fmt"
	"math"
	"os"
	"reflect"
	"sync"

	"github.com/goplus/ixgo"
	"github.com/visualfc/xtype"
	"github.com/xgo-dev/sandbox/internal/reflecttype"
	"github.com/xgo-dev/sandbox/internal/reflectxtype"
)

// internalCallback is a interface called on object completion.
//
// There are two implementations: objectDecodeState & userCallback.
type internalCallback interface {
	// source returns the dependent object. May be nil.
	source() *objectDecodeState

	// callbackRun executes the callback.
	callbackRun(ds *decodeState)
}

// userCallback is an implementation of internalCallback.
type userCallback func()

// source implements internalCallback.source.
func (userCallback) source() *objectDecodeState {
	return nil
}

// callbackRun implements internalCallback.callbackRun.
func (uc userCallback) callbackRun(*decodeState) {
	uc()
}

// objectDecodeState represents an object that may be in the process of being
// decoded. Specifically, it represents either a decoded object, or an an
// interest in a future object that will be decoded. When that interest is
// registered (via register), the storage for the object will be created, but
// it will not be decoded until the object is encountered in the stream.
type objectDecodeState struct {
	// id is the id for this object.
	id objectID

	// typ is the id for this typeID. This may be zero if this is not a
	// type-registered structure.
	typ typeID

	// obj is the object. This may or may not be valid yet, depending on
	// whether complete returns true. However, regardless of whether the
	// object is valid, obj contains a final storage location for the
	// object. This is immutable.
	//
	// Note that this must be addressable (obj.Addr() must not panic).
	//
	// The obj passed to the decode methods below will equal this obj only
	// in the case of decoding the top-level object. However, the passed
	// obj may represent individual fields, elements of a slice, etc. that
	// are effectively embedded within the reflect.Value below but with
	// distinct types.
	obj reflect.Value

	// how distinguishes handle contents from an addressable variable slot.
	how encodeStrategy

	// blockedBy is the number of dependencies this object has.
	blockedBy int

	// callbacksInline is inline storage for callbacks.
	callbacksInline [2]internalCallback

	// callbacks is a set of callbacks to execute on load.
	callbacks []internalCallback

	pendingEntry odsListElem
	leafEntry    odsListElem
}

type odsListElem struct {
	ods *objectDecodeState
	odsEntry
}

// addCallback adds a callback to the objectDecodeState.
func (ods *objectDecodeState) addCallback(ic internalCallback) {
	if ods.callbacks == nil {
		ods.callbacks = ods.callbacksInline[:0]
	}
	ods.callbacks = append(ods.callbacks, ic)
}

// findCycleFor returns when the given object is found in the blocking set.
func (ods *objectDecodeState) findCycleFor(target *objectDecodeState) []*objectDecodeState {
	for _, ic := range ods.callbacks {
		other := ic.source()
		if other != nil && other == target {
			return []*objectDecodeState{target}
		} else if childList := other.findCycleFor(target); childList != nil {
			return append(childList, other)
		}
	}

	// This should not occur.
	Failf("no deadlock found?")
	panic("unreachable")
}

// findCycle finds a dependency cycle.
func (ods *objectDecodeState) findCycle() []*objectDecodeState {
	return append(ods.findCycleFor(ods), ods)
}

// source implements internalCallback.source.
func (ods *objectDecodeState) source() *objectDecodeState {
	return ods
}

// callbackRun implements internalCallback.callbackRun.
func (ods *objectDecodeState) callbackRun(ds *decodeState) {
	ods.blockedBy--
	if ods.blockedBy == 0 {
		ds.leaves.PushBack(&ods.leafEntry)
	} else if ods.blockedBy < 0 {
		Failf("object %d has negative blockedBy: %d", ods.id, ods.blockedBy)
	}
}

// decodeState is a graph of objects in the process of being decoded.
//
// The decode process involves loading the breadth-first graph generated by
// encode. This graph is read in it's entirety, ensuring that all object
// storage is complete.
//
// As the graph is being serialized, a set of completion callbacks are
// executed. These completion callbacks should form a set of acyclic subgraphs
// over the original one. After decoding is complete, the objects are scanned
// to ensure that all callbacks are executed, otherwise the callback graph was
// not acyclic.
type decodeState struct {
	// ctx is the decode context.
	ctx context.Context

	// r is the input stream.
	r reader

	// types is the type database.
	types typeDecodeDatabase

	reflected        *reflecttype.ReflectType
	reflectx         *reflectxtype.ReflectType
	reflectxSnapshot *reflectxtype.Snapshot

	native       nativeState
	functions    []decodedFunction
	makeFuncs    map[reflect.Value]reflect.Value // Callback slots to MakeFunc wrappers.
	methodValues map[reflect.Value]reflect.Value // Method environments to reflected function wrappers.
	typeutilMaps []typeutilMap                   // Rehash after all key objects have been decoded.

	// objectByID is the set of objects in progress.
	objectsByID []*objectDecodeState

	// deferred are objects that have been read, by no interest has been
	// registered yet. These will be decoded once interest in registered.
	deferred map[objectID]object

	// pending is the set of objects that are not yet complete.
	pending odsList

	// leaves is the set of objects that have no dependencies (blockedBy == 0).
	// leaves are consumed from the front and appended to the back.
	leaves odsList

	// stats tracks time data.
	stats Stats
}

// lookup looks up an object in decodeState or returns nil if no such object
// has been previously registered.
func (ds *decodeState) lookup(id objectID) *objectDecodeState {
	if len(ds.objectsByID) < int(id) {
		return nil
	}
	return ds.objectsByID[id-1]
}

// checkComplete checks for completion.
func (ds *decodeState) checkComplete(ods *objectDecodeState) bool {
	// Still blocked?
	if ods.blockedBy > 0 {
		return false
	}

	// Track stats if relevant.
	if ods.callbacks != nil && ods.typ != 0 {
		ds.stats.start(ods.typ)
		defer ds.stats.done()
	}

	// Fire all callbacks.
	for _, ic := range ods.callbacks {
		ic.callbackRun(ds)
	}

	// Mark completed.
	ods.callbacks = nil
	ds.pending.Remove(&ods.pendingEntry)

	return true // All set.
}

// wait registers a dependency on an object.
//
// As a special case, we always allow _useable_ references back to the first
// decoding object because it may have fields that are already decoded. We also
// allow trivial self reference, since they can be handled internally.
func (ds *decodeState) wait(waiter *objectDecodeState, id objectID, callback func()) {
	switch id {
	case waiter.id:
		// Trivial self reference.
		fallthrough
	case 1:
		// Root object; see above.
		if callback != nil {
			callback()
		}
		return
	}

	// Mark as blocked.
	waiter.blockedBy++
	if waiter.blockedBy == 1 {
		ds.leaves.Remove(&waiter.leafEntry)
	}

	// No nil can be returned here.
	other := ds.lookup(id)
	if callback != nil {
		// Add the additional user callback.
		other.addCallback(userCallback(callback))
	}

	// Mark waiter as unblocked.
	other.addCallback(waiter)
}

// waitObject notes a blocking relationship.
func (ds *decodeState) waitObject(ods *objectDecodeState, encoded object, callback func()) {
	if rv, ok := encoded.(*refValue); ok && rv.Root != 0 {
		// Refs can encode pointers and maps.
		ds.wait(ods, objectID(rv.Root), callback)
	} else if sv, ok := encoded.(*sliceValue); ok && sv.Ref.Root != 0 {
		// See decodeObject; we need to wait for the array (if non-nil).
		ds.wait(ods, objectID(sv.Ref.Root), callback)
	} else if cv, ok := encoded.(*channelValue); ok && cv.Ref.Root != 0 {
		ds.wait(ods, objectID(cv.Ref.Root), callback)
	} else if iv, ok := encoded.(*interfaceValue); ok {
		// It's an interface (wait recursively).
		ds.waitObject(ods, iv.Value, callback)
	} else if rv, ok := encoded.(*reflectedValue); ok {
		ds.waitObject(ods, rv.Value, callback)
	} else if fv, ok := encoded.(*functionValue); ok && fv.Env.Root != 0 {
		ds.wait(ods, objectID(fv.Env.Root), callback)
	} else if av, ok := encoded.(*arrayValue); ok {
		blockedBy := ods.blockedBy
		for _, value := range av.Contents {
			ds.waitObject(ods, value, nil)
		}
		if callback != nil {
			if ods.blockedBy == blockedBy {
				callback()
			} else {
				ods.addCallback(userCallback(callback))
			}
		}
	} else if callback != nil {
		// Nothing to wait for: execute the callback immediately.
		callback()
	}
}

// walkChild returns a child object from obj, given an accessor path. This is
// the decode-side equivalent to traverse in encode.go.
//
// For the purposes of this function, a child object is either a field within a
// struct, an array element, or an array range, with one indirection per element in
// path. The returned value may be an unexported field, so it may not be
// directly assignable. See decode_unsafe.go.
func walkChild(path []dot, obj reflect.Value) reflect.Value {
	// See refValue.Dots. The path here is specified in reverse order.
	for i := len(path) - 1; i >= 0; i-- {
		switch pc := path[i].(type) {
		case *fieldName: // Must be a pointer.
			if obj.Kind() != reflect.Struct {
				Failf("next component in child path is a field name, but the current object is not a struct. Path: %v, current obj: %#v", path, obj)
			}
			obj = obj.FieldByName(string(*pc))
		case index: // Embedded.
			if obj.Kind() != reflect.Array {
				Failf("next component in child path is an array index, but the current object is not an array. Path: %v, current obj: %#v", path, obj)
			}
			obj = obj.Index(int(pc))
		case arrayRange:
			if obj.Kind() != reflect.Array {
				Failf("array range path requires an array, got %v", obj.Type())
			}
			if pc.start > uintValue(obj.Len()) || pc.length > uintValue(obj.Len())-pc.start {
				Failf("array range start=%d length=%d exceeds %v", pc.start, pc.length, obj.Type())
			}
			end := int(pc.start + pc.length)
			view := reflectValueRWSlice3(obj, int(pc.start), end, end)
			typ := reflect.ArrayOf(int(pc.length), obj.Type().Elem())
			obj = view.Convert(reflect.PointerTo(typ)).Elem()
		default:
			panic("unreachable: switch should be exhaustive")
		}
	}
	return obj
}

func (ds *decodeState) growObjectsByID(id objectID) {
	if len(ds.objectsByID) < int(id) {
		ds.objectsByID = append(ds.objectsByID, make([]*objectDecodeState, int(id)-len(ds.objectsByID))...)
	}
}

func (ds *decodeState) addObject(id objectID, obj reflect.Value) *objectDecodeState {
	ods := &objectDecodeState{
		id:  id,
		obj: obj,
	}
	ods.pendingEntry.ods = ods
	ods.leafEntry.ods = ods
	ds.growObjectsByID(id)
	ds.objectsByID[id-1] = ods
	ds.pending.PushBack(&ods.pendingEntry)
	ds.leaves.PushBack(&ods.leafEntry)
	return ods
}

// register registers a decode with a type.
//
// This type is only used to instantiate a new object if it has not been
// registered previously. This depends on the type provided if none is
// available in the object itself.
func (ds *decodeState) register(r *refValue, typ reflect.Type) reflect.Value {
	// Grow the objectsByID slice.
	id := objectID(r.Root)

	// Does this object already exist?
	ds.growObjectsByID(id)
	ods := ds.objectsByID[id-1]
	if ods != nil {
		return walkChild(r.Dots, ods.obj)
	}

	// Create the object.
	if r.Type != nil {
		typ = ds.findType(r.Type)
	}
	v := reflect.New(typ)
	ods = ds.addObject(id, v.Elem())

	// Process any deferred objects & callbacks.
	if encoded, ok := ds.deferred[id]; ok {
		delete(ds.deferred, id)
		ds.decodeObject(ods, ods.obj, encoded)
	}

	return walkChild(r.Dots, ods.obj)
}

// objectDecoder is for decoding structs.
type objectDecoder struct {
	// ds is decodeState.
	ds *decodeState

	// ods is current object being decoded.
	ods *objectDecodeState

	// reconciledTypeEntry is the reconciled type information.
	rte *reconciledTypeEntry

	// encoded is the encoded object state.
	encoded *structValue
}

// load is helper for the public methods on Source.
func (od *objectDecoder) load(slot int, objPtr reflect.Value, wait bool, fn func()) {
	// Note that we have reconciled the type and may remap the fields here
	// to match what's expected by the decoder. The "slot" parameter here
	// is in terms of the local type, where the fields in the encoded
	// object are in terms of the wire object's type, which might be in a
	// different order (but will have the same fields).
	v := *od.encoded.Field(od.rte.FieldOrder[slot])
	od.ds.decodeObject(od.ods, objPtr.Elem(), v)
	if wait {
		// Mark this individual object a blocker.
		od.ds.waitObject(od.ods, v, fn)
	}
}

// aterLoad implements Source.AfterLoad.
func (od *objectDecoder) afterLoad(fn func()) {
	// Queue the local callback; this will execute when all of the above
	// data dependencies have been cleared.
	od.ods.addCallback(userCallback(fn))
}

// decodeStruct decodes a struct value.
func (ds *decodeState) decodeStruct(ods *objectDecodeState, obj reflect.Value, encoded *structValue) {
	if isTypeutilMap(obj.Type()) {
		ds.typeutilMaps = append(ds.typeutilMaps, reflectValueRWAddr(obj).Interface().(typeutilMap))
	}
	if obj.Type() == reflect.TypeFor[sync.Map]() {
		ds.decodeSyncMap(ods, obj.Addr().Interface().(*sync.Map), encoded)
		return
	}
	if fields, ok := syncFields(obj); ok {
		if encoded.TypeID != 0 || encoded.Fields() != len(fields) {
			Failf("invalid synchronization value for %v", obj.Type())
		}
		obj.SetZero()
		for i, field := range fields {
			ds.decodeObject(ods, field, *encoded.Field(i))
		}
		return
	}
	if encoded.TypeID == 0 {
		if encoded.Fields() != obj.NumField() {
			Failf("struct field count %d does not match %v", encoded.Fields(), obj.Type())
		}
		for i := 0; i < obj.NumField(); i++ {
			ds.decodeObject(ods, obj.Field(i), *encoded.Field(i))
		}
		return
	}

	// Lookup the object type.
	rte := ds.types.Lookup(typeID(encoded.TypeID), obj.Type())
	ods.typ = typeID(encoded.TypeID)

	// Invoke the loader.
	od := objectDecoder{
		ds:      ds,
		ods:     ods,
		rte:     rte,
		encoded: encoded,
	}
	ds.stats.start(ods.typ)
	defer ds.stats.done()
	if sl, ok := obj.Addr().Interface().(SaverLoader); ok {
		// Note: may be a registered empty struct which does not
		// implement the saver/loader interfaces.
		sl.StateLoad(ds.ctx, Source{internal: od})
	}
}

// decodeMap decodes a map value.
func (ds *decodeState) decodeMap(ods *objectDecodeState, obj reflect.Value, encoded *mapValue) {
	if obj.IsNil() {
		// See pointerTo.
		obj.Set(reflect.MakeMap(obj.Type()))
	} else {
		obj.Clear()
	}
	for i := 0; i < len(encoded.Keys); i++ {
		// Decode the objects.
		kv := reflect.New(obj.Type().Key()).Elem()
		vv := reflect.New(obj.Type().Elem()).Elem()
		ds.decodeObject(ods, kv, encoded.Keys[i])
		ds.decodeObject(ods, vv, encoded.Values[i])
		ds.waitObject(ods, encoded.Keys[i], nil)
		ds.waitObject(ods, encoded.Values[i], nil)

		// Set in the map.
		obj.SetMapIndex(kv, vv)
	}
}

// decodeArray decodes an array value.
func (ds *decodeState) decodeArray(ods *objectDecodeState, obj reflect.Value, encoded *arrayValue) {
	if len(encoded.Contents) != obj.Len() {
		Failf("mismatching array length expect=%d, actual=%d", obj.Len(), len(encoded.Contents))
	}
	// Decode the contents into the array.
	for i := 0; i < len(encoded.Contents); i++ {
		ds.decodeObject(ods, obj.Index(i), encoded.Contents[i])
		// An inline array is a field, not its owner's completion dependency.
		// For example, A.Next[0] = B and B.Next[0] = A is an ordinary cycle.
		// Explicit LoadWait/LoadValue expands these elements in waitObject.
		if obj == ods.obj {
			ds.waitObject(ods, encoded.Contents[i], nil)
		}
	}
}

// findType finds the type for the given typeSpec.
func (ds *decodeState) findType(t typeSpec) reflect.Type {
	switch x := t.(type) {
	case *reflectedType:
		if uint64(x.ID) > uint64(^uint32(0)) {
			Failf("invalid reflect type reference %d", x.ID)
		}
		if x.reflectx {
			if ds.reflectx == nil {
				Failf("reflectx type table missing for reference %d", x.ID)
			}
			typ, err := ds.reflectx.Resolve(uint32(x.ID))
			if err != nil {
				Failf("resolve reflectx type: %w", err)
			}
			return typ
		}
		if ds.reflected == nil {
			Failf("reflect type table missing for reference %d", x.ID)
		}
		typ, err := ds.reflected.Resolve(uint32(x.ID))
		if err != nil {
			Failf("resolve reflect type: %w", err)
		}
		return typ
	case typeSpecID:
		typ := ds.types.LookupType(typeID(x))
		rte := ds.types.Lookup(typeID(x), typ)
		return rte.LocalType
	case *pointerType:
		return reflect.PtrTo(ds.findType(x.Type))
	case *arrayType:
		return reflect.ArrayOf(int(x.Count), ds.findType(x.Type))
	case *sliceType:
		return reflect.SliceOf(ds.findType(x.Type))
	case *mapType:
		return reflect.MapOf(ds.findType(x.Key), ds.findType(x.Value))
	case closureType:
		return ds.native.layout(uintptr(x), false)
	default:
		// Should not happen.
		Failf("unknown type %#v", t)
	}
	panic("unreachable")
}

// decodeInterface decodes an interface value.
func (ds *decodeState) decodeInterface(ods *objectDecodeState, obj reflect.Value, encoded *interfaceValue) {
	if _, ok := encoded.Type.(nilType); ok {
		// Special case; the nil object. Just decode directly, which
		// will read nil from the wire (if encoded correctly).
		ds.decodeObject(ods, obj, encoded.Value)
		return
	}

	// We now need to resolve the actual type.
	typ := ds.findType(encoded.Type)

	// We need to imbue type information here, then we can proceed to
	// decode normally. In order to avoid issues with setting value-types,
	// we create a new non-interface version of this object. We will then
	// set the interface object to be equal to whatever we decode.
	origObj := obj
	obj = reflect.New(typ).Elem()
	defer origObj.Set(obj)

	// With the object now having sufficient type information to actually
	// have Set called on it, we can proceed to decode the value.
	ds.decodeObject(ods, obj, encoded.Value)
}

// isFloatEq determines if x and y represent the same value.
func isFloatEq(x float64, y float64) bool {
	switch {
	case math.IsNaN(x):
		return math.IsNaN(y)
	case math.IsInf(x, 1):
		return math.IsInf(y, 1)
	case math.IsInf(x, -1):
		return math.IsInf(y, -1)
	default:
		return x == y
	}
}

// isComplexEq determines if x and y represent the same value.
func isComplexEq(x complex128, y complex128) bool {
	return isFloatEq(real(x), real(y)) && isFloatEq(imag(x), imag(y))
}

// decodeObject decodes a object value.
func (ds *decodeState) decodeObject(ods *objectDecodeState, obj reflect.Value, encoded object) {
	if obj.CanAddr() && !obj.CanSet() {
		obj = reflectValueRWAddr(obj).Elem()
	}
	checkProcessResource(obj.Type())
	switch x := encoded.(type) {
	case nilValue: // Fast path: first.
		obj.SetZero()
	case *refValue:
		if id := objectID(x.Root); id == 0 {
			obj.SetZero()
			return
		}

		// Note that if this is a map type, we go through a level of
		// indirection to allow for map aliasing.
		if obj.Kind() == reflect.Map {
			v := ds.register(x, obj.Type())
			ds.lookup(objectID(x.Root)).how = encodeMapAsValue
			if v.IsNil() {
				// Note that we don't want to clobber the map
				// if has already been decoded by decodeMap. We
				// just make it so that we have a consistent
				// reference when that eventually does happen.
				v.Set(reflect.MakeMap(v.Type()))
			}
			obj.Set(v)
			return
		}

		// Convert the pointer, retaining the registered object's storage.
		v := ds.register(x, obj.Type().Elem())
		ptr := reflectValueRWAddr(v)
		if ptr.Type() != obj.Type() {
			ptr = ptr.Convert(obj.Type())
		}
		obj.Set(ptr)
	case boolValue:
		obj.SetBool(bool(x))
	case intValue:
		obj.SetInt(int64(x))
		if obj.Int() != int64(x) {
			Failf("signed integer truncated from %v to %v", int64(x), obj.Int())
		}
	case uintValue:
		if obj.Type() == reflect.TypeFor[*os.File]() {
			if x == 0 {
				obj.SetZero()
				return
			}
			streams := []*os.File{os.Stdin, os.Stdout, os.Stderr}
			if uint64(x) > uint64(len(streams)) {
				Failf("invalid standard stream %d", x)
			}
			obj.Set(reflect.ValueOf(streams[int(x)-1]))
			return
		}
		obj.SetUint(uint64(x))
		if obj.Uint() != uint64(x) {
			Failf("unsigned integer truncated from %v to %v", uint64(x), obj.Uint())
		}
	case float32Value:
		obj.SetFloat(float64(x))
	case float64Value:
		obj.SetFloat(float64(x))
		if !isFloatEq(obj.Float(), float64(x)) {
			Failf("floating point number truncated from %v to %v", float64(x), obj.Float())
		}
	case *complex64Value:
		obj.SetComplex(complex128(*x))
	case *complex128Value:
		obj.SetComplex(complex128(*x))
		if !isComplexEq(obj.Complex(), complex128(*x)) {
			Failf("complex number truncated from %v to %v", complex128(*x), obj.Complex())
		}
	case *stringValue:
		if obj.Type() == reflect.TypeFor[*ixgo.Package]() {
			if *x == "" {
				obj.SetZero()
				return
			}
			pkg, ok := ixgo.LookupPackage(string(*x))
			if !ok {
				Failf("ixgo package %q is not registered in this process", *x)
			}
			obj.Set(reflect.ValueOf(pkg))
			return
		}
		obj.SetString(string(*x))
	case *sliceValue:
		if id := objectID(x.Ref.Root); id == 0 {
			obj.SetZero()
			return
		}
		// Note that it's fine to slice the array here and assume that
		// contents will still be filled in later on.
		typ := reflect.ArrayOf(int(x.Capacity), obj.Type().Elem()) // The object type.
		v := ds.register(&x.Ref, typ)
		obj.Set(reflectValueRWSlice3(v, 0, int(x.Length), int(x.Capacity)))
	case *arrayValue:
		ds.decodeArray(ods, obj, x)
	case *rawArrayValue:
		if !isNumericArray(obj.Type()) || uintptr(len(x.Data)) != obj.Type().Size() {
			Failf("raw array with %d bytes cannot be decoded into %v", len(x.Data), obj.Type())
		}
		copy(arrayBytes(obj), x.Data)
	case *structValue:
		ds.decodeStruct(ods, obj, x)
	case *mapValue:
		ds.decodeMap(ods, obj, x)
	case *channelValue:
		ds.decodeChannelRef(obj, x)
	case *channelData:
		ds.decodeChannel(ods, obj, x)
	case *interfaceValue:
		ds.decodeInterface(ods, obj, x)
	case *functionValue:
		ds.decodeFunction(obj, x)
	case *reflectTypeValue:
		if obj.Type() == reflect.TypeFor[xtype.Type]() {
			if _, empty := x.Type.(nilType); empty {
				obj.SetZero()
			} else {
				obj.Set(reflect.ValueOf(xtype.TypeOfType(ds.findType(x.Type))))
			}
			return
		}
		typ := ds.findType(x.Type)
		value := reflect.ValueOf(typ)
		if !value.Type().AssignableTo(obj.Type()) {
			Failf("reflect.Type cannot be assigned to %v", obj.Type())
		}
		obj.Set(value)
	case *reflectedValue:
		if obj.Type() != reflect.TypeFor[reflect.Value]() {
			Failf("reflect.Value cannot be assigned to %v", obj.Type())
		}
		if _, invalid := x.Type.(nilType); invalid {
			if _, empty := x.Value.(nilValue); !empty || x.Addressable {
				Failf("invalid zero reflect.Value")
			}
			obj.SetZero()
			return
		}
		typ := ds.findType(x.Type)
		var value reflect.Value
		if x.Addressable {
			ref, ok := x.Value.(*refValue)
			if !ok || ref.Root == 0 || typ.Kind() != reflect.Pointer {
				Failf("addressable reflect.Value requires a non-nil pointer")
			}
			value = reflect.New(typ).Elem()
			ds.decodeObject(ods, value, x.Value)
			value = value.Elem()
		} else {
			storage := reflect.New(typ).Elem()
			ds.decodeObject(ods, storage, x.Value)
			value = reflectValueUnaddressable(storage)
		}
		obj.Set(reflect.ValueOf(value))
	default:
		// Should not happen, not propagated as an error.
		Failf("unknown object %#v for %q", encoded, obj.Type().Name())
	}
}

// Load deserializes the object graph rooted at obj.
//
// This function may panic and should be run in safely().
func (ds *decodeState) Load(obj reflect.Value) {
	ds.stats.init()
	defer ds.stats.fini(func(id typeID) string {
		return ds.types.LookupName(id)
	})

	// Restore types before allocating objects that refer to their snapshot IDs.
	typeBytes, isObject, err := readHeader(&ds.r)
	if err != nil {
		Failf("type table header: %w", err)
	}
	if isObject {
		Failf("reflect type table missing")
	}
	data := ds.r.readBytes(typeBytes)
	if len(data) != 0 {
		ds.reflected, err = reflecttype.Open(data)
		if err != nil {
			Failf("import reflect types: %w", err)
		}
	}
	typeBytes, isObject, err = readHeader(&ds.r)
	if err != nil {
		Failf("reflectx type table header: %w", err)
	}
	if isObject {
		Failf("reflectx type table missing")
	}
	if data := ds.r.readBytes(typeBytes); len(data) != 0 {
		if ds.reflectxSnapshot != nil {
			ds.reflectx, err = ds.reflectxSnapshot.Open(data)
		} else {
			ds.reflectx, err = reflectxtype.Open(data)
		}
		if err != nil {
			Failf("import reflectx types: %w", err)
		}
	}

	// A returning graph already has local storage for the original IDs.
	if root := ds.lookup(1); root == nil {
		ds.addObject(1, obj)
	} else if root.obj.Type() != obj.Type() || root.obj.Addr().Pointer() != obj.Addr().Pointer() {
		Failf("root object changed during round trip")
	}
	if ds.reflectx != nil && ds.reflectx.MethodCount() != 0 {
		encoded, err := ds.r.get()
		if err != nil {
			Failf("method functions: %w", err)
		}
		methods, ok := encoded.(*arrayValue)
		if !ok || len(methods.Contents) != ds.reflectx.MethodCount() {
			Failf("method function count does not match type table")
		}
		callbacks := make([]func([]reflect.Value) []reflect.Value, len(methods.Contents))
		for i, record := range methods.Contents {
			fn, ok := record.(*reflectedValue)
			if !ok {
				Failf("invalid method function %T", record)
			}
			var function reflect.Value
			ds.decodeObject(nil, reflect.ValueOf(&function).Elem(), fn)
			if !function.IsValid() || function.Kind() != reflect.Func || function.IsNil() {
				Failf("invalid restored method function")
			}
			callbacks[i] = reflectxMethod{function: function}.call
		}
		// Allocate closure storage first, install the method table, then fill
		// the environments. Interfaces decoded below see the final Ifn entries.
		if err := ds.reflectx.SetMethods(callbacks); err != nil {
			Failf("restore reflectx methods: %w", err)
		}
	}

	// Read the number of objects.
	numObjects, isObject, err := readHeader(&ds.r)
	if err != nil {
		Failf("header error: %w", err)
	}
	if !isObject {
		Failf("object missing")
	}

	// Decode all objects.
	var (
		encoded object
		ods     *objectDecodeState
		id      objectID
	)
	if err := safely(func() {
		// Decode all objects in the stream.
		//
		// Note that the structure of this decoding loop should match the raw
		// decoding loop in state/pretty/pretty.printer.printStream().
		for i := uint64(0); i < numObjects; {
			// Unmarshal either a type object or object ID.
			encoded, err = ds.r.get()
			if err != nil {
				panic(err)
			}
			switch we := encoded.(type) {
			case *typeDescriptor:
				ds.types.Register(we)
				encoded = nil
				continue
			case uintValue:
				id = objectID(we)
				i++
				// Unmarshal and resolve the actual object.
				encoded, err = ds.r.get()
				if err != nil {
					panic(err)
				}
				ods = ds.lookup(id)
				if ods != nil {
					// Decode the object.
					ds.decodeObject(ods, ods.obj, encoded)
				} else {
					// If an object hasn't had interest registered
					// previously or isn't yet valid, we deferred
					// decoding until interest is registered.
					ds.deferred[id] = encoded
				}
				// For error handling.
				ods = nil
				encoded = nil
			default:
				Failf("wanted type or object ID, got %T", encoded)
			}
		}
	}); err != nil {
		// Include as much information as we can, taking into account
		// the possible state transitions above.
		if ods != nil {
			Failf("error decoding object ID %d (%T) from %#v: %w", id, ods.obj.Interface(), encoded, err)
		} else if encoded != nil {
			Failf("error decoding from %#v: %w", encoded, err)
		} else {
			Failf("general decoding error: %w", err)
		}
	}

	// Check if we have any deferred objects.
	numDeferred := 0
	for id, encoded := range ds.deferred {
		numDeferred++
		if s, ok := encoded.(*structValue); ok && s.TypeID != 0 {
			typ := ds.types.LookupType(typeID(s.TypeID))
			Failf("unused deferred object: ID %d, type %v", id, typ)
		} else {
			Failf("unused deferred object: ID %d, %#v", id, encoded)
		}
	}
	if numDeferred != 0 {
		Failf("still had %d deferred objects", numDeferred)
	}

	// Validate all closure storage before callbacks can invoke a restored func.
	for _, f := range ds.functions {
		if f.storage.Field(0).Uint() != uint64(f.pc) {
			Failf("closure storage does not match PC %#x", f.pc)
		}
	}
	for callback, fn := range ds.makeFuncs {
		makeFuncCallback(fn).Set(callback)
	}
	for storage, fn := range ds.methodValues {
		env := storage.Addr().Interface().(*methodValueEnv)
		method := env.receiver.Method(env.method)
		if !method.Type().ConvertibleTo(fn.Type()) {
			Failf("restored method has type %v, want %v", method.Type(), fn.Type())
		}
		*methodValueStorage(fn) = *methodValueStorage(method.Convert(fn.Type()))
	}
	for _, m := range ds.typeutilMaps {
		rehashTypeutilMap(m)
	}

	// Scan and fire all callbacks. We iterate over the list of incomplete
	// objects until all have been finished. We stop iterating if no
	// objects become complete (there is a dependency cycle).
	//
	// Note that we iterate backwards here, because there will be a strong
	// tendency for blocking relationships to go from earlier objects to
	// later (deeper) objects in the graph. This will reduce the number of
	// iterations required to finish all objects.
	if err := safely(func() {
		for elem := ds.leaves.Front(); elem != nil; elem = elem.Next() {
			ods = elem.ods
			ds.checkComplete(elem.ods)
		}
	}); err != nil {
		Failf("error executing callbacks: %w\nfor object %#v", err, ods.obj.Interface())
	}

	// Check if we have any remaining dependency cycles. If there are any
	// objects left in the pending list, then it must be due to a cycle.
	if elem := ds.pending.Front(); elem != nil {
		// Temporary diagnostics: callbacks point from a dependency to its
		// waiters, so invert those edges to show what each pending object needs.
		dependencies := make(map[objectID][]objectID)
		for _, dependency := range ds.objectsByID {
			if dependency == nil {
				continue
			}
			for _, callback := range dependency.callbacks {
				if waiter := callback.source(); waiter != nil {
					dependencies[waiter.id] = append(dependencies[waiter.id], dependency.id)
				}
			}
		}
		leaves := make(map[objectID]bool)
		for leaf := ds.leaves.Front(); leaf != nil; leaf = leaf.Next() {
			leaves[leaf.ods.id] = true
		}
		fmt.Fprintf(os.Stderr, "state decode incomplete: objects=%d pending=%d leaves=%d deferred=%d\n", len(ds.objectsByID), ds.pending.Len(), len(leaves), len(ds.deferred))
		for pending := ds.pending.Front(); pending != nil; pending = pending.Next() {
			object := pending.ods
			fmt.Fprintf(os.Stderr, "state pending: id=%d type=%v blocked_by=%d in_leaves=%t callbacks=%d waits_for=%v\n", object.id, object.obj.Type(), object.blockedBy, leaves[object.id], len(object.callbacks), dependencies[object.id])
		}
		// This must be the result of a dependency cycle.
		cycle := elem.ods.findCycle()
		var buf bytes.Buffer
		buf.WriteString("dependency cycle: {")
		for i, cycleOS := range cycle {
			if i > 0 {
				buf.WriteString(" => ")
			}
			fmt.Fprintf(&buf, "%q", cycleOS.obj.Type())
		}
		buf.WriteString("}")
		Failf("incomplete graph: %s", buf.String())
	}
}

// readHeader reads an object header.
//
// Each object written to the statefile is prefixed with a header. See
// writeHeader for more information.
func readHeader(r *reader) (length uint64, object bool, err error) {
	// Read the header.
	err = safely(func() {
		length = uint64(loadUint(r))
	})
	if err != nil {
		// On the header, pass raw I/O errors.
		if sErr, ok := err.(*ErrState); ok {
			return 0, false, sErr.Unwrap()
		}
	}

	// Decode whether the object is valid.
	object = length&objectFlag != 0
	length &^= objectFlag
	return
}
